# Generated by Django 4.0 on 2024-12-02 11:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_group', models.CharField(max_length=100, verbose_name='عنوان گروه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 958219, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': 'گروه سرویس',
                'verbose_name_plural': 'گروه های سرویس',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان خدمات')),
                ('summery', models.TextField(verbose_name='توضیح کوتاه')),
                ('decription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='2توضیحات')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 958503, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسلاگ')),
                ('decription_meta', models.TextField(blank=True, null=True, verbose_name='توضیجان متا')),
                ('group_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_service', to='services.groupservice', verbose_name='گروه سرویس ها')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
        migrations.CreateModel(
            name='Service_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('Serviceice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_service', to='services.service', verbose_name='گروه سرویس ها')),
            ],
        ),
        migrations.CreateModel(
            name='Meta_tag_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_meta', to='services.service')),
            ],
        ),
    ]
