# Generated by Django 4.0.3 on 2024-12-29 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_groupservice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupservice',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 610957, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 611272, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='service_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
