# Generated by Django 4.0.3 on 2025-01-13 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_groupservice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupservice',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 23, 15, 60506, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 23, 15, 60814, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='service_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
