# Generated by Django 4.0.3 on 2025-01-13 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_groupservice_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city_link',
            field=models.TextField(blank=True, null=True, verbose_name='لینک شهر'),
        ),
        migrations.AlterField(
            model_name='groupservice',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 54, 57, 93708, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 54, 57, 94076, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='service_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
