# Generated by Django 4.0 on 2024-12-02 11:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='حروف')),
                ('decription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='2توضیحات')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 957405, tzinfo=utc), verbose_name='تاریخ ثبت ')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='ManyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 957713, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('video', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ودیو')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات',
            },
        ),
    ]
