# Generated by Django 4.0 on 2024-12-02 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 55, 13, 229861, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='manyquestion',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 55, 13, 230251, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='manyquestion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ودیو'),
        ),
    ]
