# Generated by Django 4.0 on 2024-12-02 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 55, 13, 239370, tzinfo=utc), verbose_name='تاریخ'),
        ),
    ]
