# Generated by Django 4.0.3 on 2024-12-04 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image_name_alter_comment_register_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 971754, tzinfo=utc), verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 971762, tzinfo=utc), verbose_name='اپدیت شده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 973395, tzinfo=utc), verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='meta_tag_model',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 972759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meta_tag_model',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 972772, tzinfo=utc)),
        ),
    ]
