# Generated by Django 4.0.3 on 2024-12-04 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_image_name_alter_blog_register_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='meta_tag_model',
            options={},
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='register_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='اپدیت شده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 52, 17, 627651, tzinfo=utc), verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='meta_tag_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meta_tag_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
