# Generated by Django 4.0.3 on 2024-12-12 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_options_alter_meta_tag_model_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 6, 28, 3, 355172, tzinfo=utc), verbose_name='تاریخ'),
        ),
    ]
