# Generated by Django 4.0.3 on 2024-12-29 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image_name_alter_blog_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 620106, tzinfo=utc), verbose_name='تاریخ'),
        ),
    ]
