# Generated by Django 4.0.3 on 2025-01-13 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_city_link_alter_blog_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 54, 57, 103045, tzinfo=utc), verbose_name='تاریخ'),
        ),
    ]
