# Generated by Django 4.0 on 2024-12-02 11:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(max_length=100, verbose_name='تلفن شرکت')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='یمیل')),
                ('address', models.TextField(verbose_name='ادرس')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 955872, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 955886, tzinfo=utc), verbose_name='تاریخ اپدیت')),
                ('address_link', models.CharField(max_length=1000, verbose_name='ادرس لینک گوکل')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('video', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ودیو')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات درباره شرکت',
            },
        ),
        migrations.CreateModel(
            name='Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social', models.CharField(max_length=20, verbose_name='نام شبکه اجتماعی')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='ادرس ایکون شبکه اجتماعی')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('address_link', models.CharField(max_length=1000, verbose_name='ادرس لینک ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_company', to='company.company_information', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماهی',
            },
        ),
        migrations.CreateModel(
            name='Resum_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('decription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='2توضیحات')),
                ('title_subject', models.CharField(max_length=10, verbose_name='نتیجه')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 956331, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('letter', models.CharField(blank=None, max_length=10, null=True, verbose_name='تک  کلمه ای')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resum_com', to='company.company_information', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'رزومه شرکت',
                'verbose_name_plural': 'رزومه های شرکت',
            },
        ),
    ]
