# Generated by Django 4.0.3 on 2024-12-29 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_information_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_information',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 608473, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 608481, tzinfo=utc), verbose_name='تاریخ اپدیت'),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ودیو'),
        ),
        migrations.AlterField(
            model_name='resum_company',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='resum_company',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 608966, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
