# Generated by Django 4.0 on 2024-12-02 11:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=100, verbose_name='عنوان مقدار')),
                ('english_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='مقدار انگلیسی')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_value', to='project.feature', verbose_name='ویژگی')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پروزه')),
                ('is_active', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 960579, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
            ],
        ),
        migrations.CreateModel(
            name='MemeberCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('cerfigicated', models.CharField(max_length=100, verbose_name='عضو شرکت')),
                ('is_active', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 963418, tzinfo=utc), verbose_name='تاریخ ثبت ')),
            ],
            options={
                'verbose_name': 'عضو شرکت',
                'verbose_name_plural': 'اعضای شرکت',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان خدمات')),
                ('summery', models.TextField(verbose_name='توضیح کوتاه')),
                ('decription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='2توضیحات')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسلاگ')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 961506, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='مقدار پروژه')),
                ('english', models.CharField(blank=True, max_length=20, null=True, verbose_name='انگلیسی')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.feature', verbose_name='ویژگی')),
                ('filter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.featurevalue', verbose_name='فیلترینگ مقدار')),
                ('project_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_value', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'ویژگی پروژه ها',
                'verbose_name_plural': 'ویژگی های پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='project_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_project', to='project.project', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(through='project.ProjectFeature', to='project.Feature'),
        ),
        migrations.AddField(
            model_name='project',
            name='group_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group_Project', to='project.groupproject', verbose_name='گروه سرویس ها'),
        ),
        migrations.CreateModel(
            name='Meta_tag_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projedct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_meta', to='project.project')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='Project_group',
            field=models.ManyToManyField(related_name='features_of_group', to='project.GroupProject', verbose_name='گروه پروژه'),
        ),
    ]
