# Generated by Django 4.0 on 2024-12-02 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproject',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 55, 13, 232432, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 55, 13, 235777, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 13, 55, 13, 233355, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
