# Generated by Django 4.0 on 2024-12-02 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_groupproject_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproject',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 14, 3, 51, 506328, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 14, 3, 51, 509659, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 14, 3, 51, 507240, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
