# Generated by Django 4.0.3 on 2024-12-04 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_groupproject_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproject',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 965022, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 967982, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 7, 5, 5, 966049, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
