# Generated by Django 4.0.3 on 2025-01-13 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_groupproject_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproject',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 23, 15, 62283, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 23, 15, 65269, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 7, 23, 15, 63303, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
