# Generated by Django 4.0.3 on 2025-08-23 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_groupproject_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproject',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 6, 57, 38, 655668, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='memebercompany',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 6, 57, 38, 658421, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 6, 57, 38, 656604, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='project_gallery',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='ادرس عکس'),
        ),
    ]
