# Generated by Django 4.0 on 2024-12-02 11:17

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='2توضیحات')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 954934, tzinfo=utc), verbose_name='تاریخ ثبت ')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
        migrations.CreateModel(
            name='GalleryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2024, 12, 2, 11, 17, 19, 955272, tzinfo=utc), verbose_name='تاریخ ثبت ')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_img', to='main.main_slider', verbose_name='اسلایدر')),
            ],
        ),
    ]
