# Generated by Django 4.0.3 on 2024-12-29 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_gallerymain_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymain',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین '),
        ),
        migrations.AlterField(
            model_name='gallerymain',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='gallerymain',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 607842, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='main_slider',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 53, 50, 607485, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
    ]
