# Generated by Django 4.0.3 on 2025-08-23 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import funcs


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_gallerymain_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymain',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='gallerymain',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 6, 57, 53, 349418, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='main_slider',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 23, 6, 57, 53, 349113, tzinfo=utc), verbose_name='تاریخ ثبت '),
        ),
    ]
